services:
  - type: web
    name: amazon-affiliate-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    autoDeploy: true

cronJobs:
  - name: run-bot-every-3-hours
    schedule: "0 */3 * * *"
    command: "python bot.py"
    service: amazon-affiliate-bot
