services:
  - type: worker
    name: amazon-affiliate-bot
    runtime: docker
    repo: https://github.com/faziolifabrizio-jpg/risparmioevoluto
    branch: main
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    plan: free
    cronSchedule:
      - "0 9 * * *"
      - "0 21 * * *"
